version: '2'
services:
  spec:
    extends:
      file: ../docker-compose.yml
      service: spec
    environment:
      CURRENT_ADAPTER: pg
    depends_on:
      - pg
  pg:
    image: postgres:${PG_VERSION}
    environment:
      POSTGRES_PASSWORD: pass
